server:
  port: 8080

spring:
  application:
    name: "RepositoryManager"
  datasource:
    url: jdbc:h2:file:./data/database
    driver-class-name: org.h2.Driver
    username: danbo
    password: danbo
  jpa:
    open-in-view: false