server:
  port: 8080

sentry:
  dsn: ""

spring:
  application:
    name: "RepositoryManager"
  datasource:
    url: jdbc:h2:file:./data/database
    driver-class-name: org.h2.Driver
    username: danbo
    password: danbo

repository-manager:
  allow-registration: false
  base-url: "http://localhost:8080"
  default-platform: "wii"
  repo-dir: "repository"
  generate-wsc-banner: false
  banner-generator-path: "BannerGenerator"
  protected-users: [1]
  discord:
    enable-logging: false
    catalog-webhook-url: ""
    log-webhook-url: ""
  fetch:
    timeout: 60
    user-agent: "RepositoryManager-DEV"
    secret-user-agents: {}
    github-token: ""
    itchio-token: ""